export const dummyMetadata = {
  name: 'devinsight-sample',
  fullName: 'example/devinsight-sample',
  description: 'A sample repository for testing DevInsight',
  stars: 42,
  forks: 7,
  watchers: 10,
  language: 'TypeScript',
  topics: ['nextjs', 'analysis', 'ai', 'developer-tools'],
  license: 'MIT',
  defaultBranch: 'main',
  isFork: false,
  isArchived: false,
  isTemplate: false,
  openIssues: 3,
  sizeKB: 512,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-02-01T00:00:00Z',
  pushedAt: '2024-02-10T00:00:00Z',
}
